services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
    networks:
      - default

  beschrapi:
    image: padi2312/beschrapi:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./static:/app/static # Path to static files
      - ./config.bscrp.yaml:/app/config.bscrp.yaml # Path to the config file
      - ./code:/app/code # Path to referenced code files in config
    networks:
      - default

networks:
  default:
